gamemode-aliases:
  enabled: true
toggle-connection-msgs:
  enabled: true
  on-msg: "&aConnection messages are now SHOWN"
  off-msg: "&cConnection messages are now HIDDEN"
help:
  enabled: true
  message:
    - ""
    - ""
    - ""
kill:
  enabled: true
spawn:
  enabled: true
  teleport-onjoin: true
  teleport-ondeath: true
  location:
    x:
    y:
    z:
    yaw:
    world:
  messages:
    first-join-message: "&b%player% has connected for the first time"
    join-message: "&7%player% connected"
    quit-message: "&7%player% disconnected"
only-proxy-join:
  enabled: true
  whitelist:
    - 127.0.0.1
  kick-message: '&cYou have to join through the proxy.'